name: CMake

on: [push]

jobs:

  # Job for building on Ubuntu
  Ubuntu:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
          - name: Ubuntu gcc Debug
            os: ubuntu-latest
            build_type: Debug
            compiler_cc: /usr/bin/gcc
            compiler_cxx: /usr/bin/g++
          - name: Ubuntu gcc Release
            os: ubuntu-latest
            build_type: Release
            compiler_cc: /usr/bin/gcc
            compiler_cxx: /usr/bin/g++
          - name: Ubuntu clang Debug
            os: ubuntu-latest
            build_type: Debug
            compiler_cc: /usr/bin/clang
            compiler_cxx: /usr/bin/clang++
          - name: Ubuntu clang Release
            os: ubuntu-latest
            build_type: Release
            compiler_cc: /usr/bin/clang
            compiler_cxx: /usr/bin/clang++

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/out

    - name: Configure CMake
      run: cmake -S . -B ${{github.workspace}}/out -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/out

    - name: Test
      run: ${{github.workspace}}/out/tests/unittests

    - name: Install
      run: sudo cmake --install ${{github.workspace}}/out

    - name: Configure Test CMake
      run: cmake -S ${{github.workspace}}/cmake/tests -B ${{github.workspace}}/cmake/tests/out

    - name: Build Test CMake
      run: cmake --build ${{github.workspace}}/cmake/tests/out

  # Job for building on macOS
  macOS:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
          - name: macOS clang Debug
            os: macos-latest
            build_type: Debug
          - name: macOS clang Release
            os: macos-latest
            build_type: Release
    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/out

    - name: Configure CMake
      run: cmake -S . -B ${{github.workspace}}/out -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/out

    - name: Test
      run: ${{github.workspace}}/out/tests/unittests

  # Job for building on Windows
  Windows:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
            - name: Windows vc++ Debug
              os: windows-latest
              build_type: Debug
            - name: Windows vc++ Release
              os: windows-latest
              build_type: Release

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/out

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} -DBUILD_TESTS=ON -S . -B ${{github.workspace}}/out

    - name: Build
      run: cmake --build ${{github.workspace}}/out --config ${{matrix.config.build_type}}

    - name: Test
      run: ${{github.workspace}}/out/tests/${{matrix.config.build_type}}/unittests.exe
